#DataSource Configuration
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-rest?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
server:
  servlet:
    contextPath: /api